include:
  - remote: 'https://raw.githubusercontent.com/jobtome-labs/ci-templates/v2.7.0/helm-quality.yml'

# EUROPE
deploy:production:europe:helm:
  extends: .deploy:production:helm
  variables:
    GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_EUROPE}
    CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_EUROPE}
    CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION_EUROPE}
    DOMAIN: ${DOMAIN_PRODUCTION_EUROPE}
    SECRET_YAML: ${SECRET_YAML_PRODUCTION_EUROPE}
    NAMESPACE: ${NAMESPACE_PRODUCTION_EUROPE}
    ENVIRONMENT: production
    ENVIRONMENT_NAME: production-europe
    ENVIRONMENT_PATH: ${ENVIRONMENT_PATH_EUROPE}
  before_script:
    - |
      # CHECK VARIABLES PHASE
      for var in "GOOGLE_KEY_PRODUCTION_EUROPE" "CLUSTER_NAME_PRODUCTION_EUROPE" "CLUSTER_ZONE_PRODUCTION_EUROPE"; do
          if [ -z "${!var}" ]; then
            echo "Missing '${var}' variable!"
            exit 1
          fi
      done

# AMERICA
deploy:production:america:helm:
  extends: .deploy:production:helm
  variables:
    GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_AMERICA}
    CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_AMERICA}
    CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION_AMERICA}
    DOMAIN: ${DOMAIN_PRODUCTION_AMERICA}
    SECRET_YAML: ${SECRET_YAML_PRODUCTION_AMERICA}
    NAMESPACE: ${NAMESPACE_PRODUCTION_AMERICA}
    ENVIRONMENT: production
    ENVIRONMENT_NAME: production-america
    ENVIRONMENT_PATH: ${ENVIRONMENT_PATH_AMERICA}
  before_script:
    - |
      # CHECK VARIABLES PHASE
      for var in "GOOGLE_KEY_PRODUCTION_AMERICA" "CLUSTER_NAME_PRODUCTION_AMERICA" "CLUSTER_ZONE_PRODUCTION_AMERICA"; do
          if [ -z "${!var}" ]; then
            echo "Missing '${var}' variable!"
            exit 1
          fi
      done

# ASIA
deploy:production:asia:helm:
  extends: .deploy:production:helm
  variables:
    GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_ASIA}
    CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_ASIA}
    CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION_ASIA}
    DOMAIN: ${DOMAIN_PRODUCTION_ASIA}
    SECRET_YAML: ${SECRET_YAML_PRODUCTION_ASIA}
    NAMESPACE: ${NAMESPACE_PRODUCTION_ASIA}
    ENVIRONMENT: production
    ENVIRONMENT_NAME: production-asia
    ENVIRONMENT_PATH: ${ENVIRONMENT_PATH_ASIA}
  before_script:
    - |
      # CHECK VARIABLES PHASE
      for var in "GOOGLE_KEY_PRODUCTION_ASIA" "CLUSTER_NAME_PRODUCTION_ASIA" "CLUSTER_ZONE_PRODUCTION_ASIA"; do
          if [ -z "${!var}" ]; then
            echo "Missing '${var}' variable!"
            exit 1
          fi
      done
